apiVersion: v2
appVersion: "1.0"
description: A Helm chart for adoption-web App
name: adoption-web
home: https://github.com/hmcts/adoption-web
version: 0.0.1
dependencies:
  - name: nodejs
    version: 2.3.8
    repository: '@hmctspublic'

