Feature: Form failures

  Background:
    Given I create a new user and login

    @nightly
    Scenario: They fail to fill out the applicant 1 forms
    Given I go to "/your-details"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/irretrievable-breakdown"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/date-from-certificate"
    And I click "Continue"
    Then the page should include "You have not entered a date. Enter a date to continue."
    Given I select "Day"
    And I type "!"
    Given I select "Month"
    And I type "1"
    Given I select "Year"
    And I type "abc"
    When I click "Continue"
    Then the page should include "You have entered an invalid date. Enter the date using the following format: 31 3 2002"
    Given I clear the form
    And I enter a date 2 years ahead
    When I click "Continue"
    Then the page should include "You have entered a date that is in the future. Enter a date that is in the past before continuing."
    Given I clear the form
    And I enter a date 6 months ago
    When I click "Continue"
    Then the page should include "You have not been married long enough to apply for a divorce"
    Given I go to "/do-you-have-your-certificate"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/help-with-your-fee"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/have-you-applied-for-help-with-fees"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I select "Yes"
    When I click "Continue"
    Then the page should include "You need to enter your Help With Fees reference number before continuing. You received this when you applied."
    Given I select "Enter your Help With Fees reference number"
    And I type "invalid"
    When I click "Continue"
    Then the page should include "You have entered an invalid Help With Fees reference number. Check the number and enter it again."
    Given I go to "/how-do-you-want-to-apply"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/their-email-address"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not entered their email address or said you do not know it. You have to do one or the other before continuing."
    Given I select "Your partner's email address"
    And I type "test.com"
    When I click "Continue"
    Then the page should include "You have entered an invalid email address. Check it and enter it again before continuing."
    Given I clear the form
    And I select "Your partner's email address"
    And I type "simulate-delivered@notifications.service.gov.uk"
    And I select "I do not know their email address"
    When I click "Continue"
    Then the page should include "You have entered an email address and indicated that you do not know their email address. You can only do one before continuing."
    Given I go to "/do-you-have-address"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/other-court-cases"
    And I clear the form
    And I click "Continue"
    Then the page should include "There was a problem"
    Given I go to "/details-other-proceedings"
    And I clear the form
    And I click "Continue"
    Then the page should include "There was a problem"
    Given I go to "/enter-their-address"
    When I click "Find address"
    Then the page should include "You have not entered your partner’s postcode. Enter their postcode before continuing."
    Given I reset the postcode lookup form
    And I select "Enter a UK postcode"
    And I type "not a postcode!"
    When I click "Find address"
    Then the page should include "You have not entered a valid UK postcode. Enter a valid UK postcode before continuing."
    Given I reset the postcode lookup form
    And I select "Enter a UK postcode"
    And I type "SW1H 9AJ"
    And I click "Find address"
    And I click "I cannot find the address in the list"
    And I click "Continue"
    Then the page should include "You have not entered your partner’s building and street address. Enter their building and street address before continuing."
    And the page should include "You have not entered your partner’s town or city. Enter their town or city before continuing."
    And the page should include "You have not entered your partner’s postcode. Enter their postcode before continuing."
    Given I reset the postcode lookup form
    And I click "I cannot enter a UK postcode"
    When I click "Continue"
    Then the page should include "You have not entered your partner’s building and street address. Enter their building and street address before continuing."
    And the page should include "You have not entered your partner’s country. Enter their country before continuing."
    Given I go to "/in-the-uk"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/certificate-in-english"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/certified-translation"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/country-and-place"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to enter the country."
    And the page should include "You have not answered the question. You need to enter the place."
    Given I go to "/where-your-lives-are-based"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/enter-your-name"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not entered your first name. Enter it before continuing."
    And the page should include "You have not entered your last name. Enter it before continuing."
    Given I clear the form
    When I select "Your first name"
    And I type "My first name!"
    And I select "Your last name"
    And I type "My last-name1"
    And I click "Continue"
    Then the page should include "You have entered an invalid character, like a number. Enter your name using letters only."
    Given I go to "/enter-their-name"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not entered their first name. Enter it before continuing."
    And the page should include "You have not entered their last name. Enter it before continuing."
    Given I clear the form
    When I select "Your partner’s first name(s)"
    And I type "Their first name!"
    And I select "Your partner’s last name(s)"
    And I type "Their last-name1"
    And I click "Continue"
    Then the page should include "You have entered an invalid character, like a number. Enter their name using letters only."
    Given I go to "/your-names-on-certificate"
    When I click "Continue"
    Then the page should include "You have not entered anything. Enter your full name as it appears on your marriage certificate."
    And the page should include "You have not entered anything. Enter their full name as it appears on your marriage certificate."
    Given I select "Copy your full name from the marriage certificate"
    And I type "Firstname Lastname1"
    And I select "Copy your partner's full name from the marriage certificate"
    And I type "Husbands name1"
    And I click "Continue"
    Then the page should include "You have entered an invalid character, like a number. Enter your name using letters only."
    Given I go to "/changes-to-your-name"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/how-did-you-change-your-name"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I select "Another way"
    When I click "Continue"
    Then the page should include "You have said you changed your name another way but not provided details. Provide details of how you changed your name."
    Given I go to "/how-the-court-will-contact-you"
    And I click "Continue"
    Then the page should include "You have to agree to receive email notifications in order to use this online service."
    Given I clear the form
    And I select "I agree that the divorce service can send me notifications and serve (deliver) court documents to me by email."
    When I select "Enter your phone number (optional)"
    And I type "12345"
    And I click "Continue"
    Then the page should include "The phone number you have entered is invalid. Enter a valid phone number to continue."
    Given I go to "/english-or-welsh"
    When I select "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/address-private"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/enter-your-address"
    When I click "Find address"
    Then the page should include "You have not entered your postcode. Enter your postcode before continuing."
    Given I select "Enter a UK postcode"
    And I type "ZZ00 0ZZ"
    And I click "Find address"
    And I click "I cannot find the address in the list"
    When I click "Continue"
    Then the page should include "You have not entered your building and street address. Enter your building and street address before continuing."
    And the page should include "You have not entered your town or city. Enter your town or city before continuing."
    And the page should include "You have not entered your postcode. Enter your postcode before continuing."
    Given I reset the postcode lookup form
    And I select "Enter a UK postcode"
    And I type "SW1H 9AJ"
    When I click "Find address"
    Then the page should include "SW1H 9AJ"
    Given I wait for the postcode lookup to return results
    And I click "Continue"
    Then the page should include "You have not selected your address. Select your address from the list before continuing."
    Given I go to "/details-other-proceedings"
    When I click "Continue"
    Then the page should include "You have not provided any information. You need to enter details of the other legal proceedings."
    Given I go to "/do-you-want-to-apply-financial-order"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/upload-your-documents"
    When I click "Continue"
    Then the page should include "You have not uploaded anything. Either upload your document or select that you cannot upload your documents."
    Given I go to "/how-do-you-want-to-apply"
    And I select "I want to apply jointly, with my partner"
    When I click "Continue"
    Then the page URL should be "/their-email-address"
    Given I go to "/their-email-address"
    When I click "Continue"
    Then the page should include "You have not entered their email address. You have to enter their email address to do a joint application."
    Given I've already completed the form using the fixture "completeCase"
    And I go to "/check-your-answers"
    When I click "Continue"
    Then the page should include "You have not confirmed what you are applying to the court to do. You need to confirm before continuing."
    And the page should include "You have not confirmed that you believe the facts in the application are true. You need to confirm before continuing."

  @nightly
  Scenario: They fail to fill out the applicant 1 joint application forms
    Given I go to "/how-do-you-want-to-apply"
    And I select "I want to apply jointly, with my partner"
    When I click "Continue"
    Then the page URL should be "/their-email-address"
    Given I click "Continue"
    Then the page should include "You have not entered their email address. You have to enter their email address to do a joint application."

  @nightly
  Scenario: They fail to fill out the respondent forms
    Given I've already completed the form using the fixture "completeCase"
    And I go to '/check-your-answers'
    And I click "I confirm"
    And I click "I believe that the facts stated in this application are true"
    When I click "Continue to payment"
    And I pay and submit the application
    Then the page should include "Application submitted"
    Given a case worker issues the application
    And I enter my valid case reference and valid access code
    Then the page URL should be "/respondent/hub-page"
    When I click "Respond to the application"
    Then the page URL should be "/respondent/review-the-application"
    And the page should include "Review the divorce application"
    And I click "Continue"
    Then the page should include "You need to confirm that you have read the application before you continue."
    Given I select "I have read the application for divorce"
    And I click "Continue"
    Then the page URL should be "/respondent/how-do-you-want-to-respond"
    Given I clear the form
    When I click "Continue"
    Then the page should include "You need to select how you want to respond before continuing."
    When I go to "/respondent/disputing-the-application"
    And I clear the form
    And I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    When I go to "/respondent/legal-jurisdiction-of-the-courts"
    And I clear the form
    And I click "Continue"
    Then the page should include "There was a problem"
    When I select "No, I do not agree the courts have jurisdiction"
    And I click "Continue"
    Then the page should include "You need to explain why you think the courts of England and Wales do not have the legal power (jurisdiction) to grant your divorce"
    And the page should include "You need to tell us which country your life is mainly based"
    When I go to "/respondent/other-court-cases"
    And I clear the form
    And I click "Continue"
    Then the page should include "There was a problem"
    When I go to "/respondent/details-other-proceedings"
    And I clear the form
    And I click "Continue"
    Then the page should include "There was a problem"
    When I go to "/respondent/how-the-court-will-contact-you"
    And I clear the form
    And I click "Continue"
    Then the page should include "There was a problem"
    And the page should include "You have to agree to receive email notifications in order to use this online service."
    When I go to "/respondent/english-or-welsh"
    And I clear the form
    And I click "Continue"
    Then the page should include "There was a problem"
    Given I've already completed the form using the fixture "respondentCompleteCase"
    And I go to "/respondent/check-your-answers"
    And I click "Submit"
    Then the page should include "You have not confirmed that you are the respondent and that you believe the facts in the application are true. You need to confirm before continuing."

  @nightly
  Scenario: They fail to fill out the applicant 2 forms
    Given I've already completed the form using the fixture "jointApplicant1CompleteCase"
    When I go to "/check-your-answers"
    And I click "Send for review"
    Then the page URL should be "/application-sent-for-review"
    When I enter my valid case reference and valid access code
    Then the page should include "You need to review your joint application"
    When I click "Continue"
    Then the page URL should be "/applicant2/irretrievable-breakdown"
    Given I clear the form
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/applicant2/help-with-your-fee"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/applicant2/have-you-applied-for-help-with-fees"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I select "Yes"
    When I click "Continue"
    Then the page should include "You need to enter your Help With Fees reference number before continuing. You received this when you applied."
    Given I go to "/applicant2/enter-your-name"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not entered your first name. Enter it before continuing."
    And the page should include "You have not entered your last name. Enter it before continuing."
    Given I select "Your first name"
    And I type "My first name!"
    And I select "Your last name"
    And I type "My last-name1"
    When I click "Continue"
    Then the page should include "You have entered an invalid character, like a number. Enter your name using letters only."
    Given I go to "/applicant2/changes-to-your-name"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/applicant2/how-did-you-change-your-name"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I select "Another way"
    When I click "Continue"
    Then the page should include "You have said you changed your name another way but not provided details. Provide details of how you changed your name."
    Given I go to "/applicant2/how-the-court-will-contact-you"
    And I clear the form
    And I select "Enter your phone number (optional)"
    And I type "12345"
    When I click "Continue"
    Then the page should include "You have to agree to receive email notifications in order to use this online service."
    And the page should include "The phone number you have entered is invalid. Enter a valid phone number to continue."
    Given I go to "/applicant2/english-or-welsh"
    And I clear the form
    When I select "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/applicant2/address-private"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/applicant2/enter-your-address"
    And I clear the form
    When I click "Find address"
    Then the page should include "You have not entered your postcode. Enter your postcode before continuing."
    Given I select "Enter a UK postcode"
    And I type "ZZ00 0ZZ"
    And I click "Find address"
    And I click "I cannot find the address in the list"
    When I click "Continue"
    Then the page should include "You have not entered your building and street address. Enter your building and street address before continuing."
    And the page should include "You have not entered your town or city. Enter your town or city before continuing."
    And the page should include "You have not entered your postcode. Enter your postcode before continuing."
    Given I reset the postcode lookup form
    And I select "Enter a UK postcode"
    And I type "SW1H 9AJ"
    When I click "Find address"
    Then the page should include "SW1H 9AJ"
    Given I wait for the postcode lookup to return results
    And I click "Continue"
    Then the page should include "You have not selected your address. Select your address from the list before continuing."
    Given I go to "/applicant2/other-court-cases"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/applicant2/details-other-proceedings"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not provided any information. You need to enter details of the other legal proceedings."
    Given I go to "/applicant2/do-you-want-to-apply-financial-order"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I go to "/applicant2/how-to-apply-financial-order"
    When I click "Continue"
    Then the page URL should be "/applicant2/check-your-joint-application"
    Given I go to "/applicant2/upload-your-documents"
    And I clear the form
    And I select "I cannot upload some or all of my documents"
    When I click "Continue"
    Then the page should include "You have not uploaded anything. Either upload your document or select that you cannot upload your documents."
    And the page should include "Select which file you could not upload before continuing."
    Given I go to "/applicant2/check-your-joint-application"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I select "No"
    When I click "Continue"
    Then the page should include "You have not answered the question. You need to select an answer before continuing."
    Given I've already completed the form using the fixture "jointApplicant2CompleteCase" for applicant 2
    And I go to "/applicant2/upload-your-documents"
    And I select "I cannot upload some or all of my documents"
    When I click "Continue"
    Then the page should include "Select which file you could not upload before continuing."
    Given I go to "/applicant2/confirm-your-joint-application"
    And I clear the form
    When I click "Continue"
    Then the page should include "You have not confirmed what you are applying to the court to do. You need to confirm before continuing."
    And the page should include "You have not confirmed that you believe the facts in the application are true. You need to confirm before continuing."
