import { IdamUtils } from '@hmcts/playwright-common';
import { APIRequestContext, request } from '@playwright/test';
import { AxiosResponse } from 'axios';

import { getServiceAuthToken, getTokenFromApi } from '../../src/main/app/auth/service/get-service-auth-token';
import { getAccessToken } from '../helpers/caseCreaterHelper';

import { urlConfig } from './urls';

export class CaseHelperUtils {
  [x: string]: any;
  constructor(private caseType: string = 'A58', private idamUtils: IdamUtils) {}

  private async createApiContext(): Promise<APIRequestContext> {
    return request.newContext({});
  }

  /**
   * Method to create blank case
   * @param userId
   * @param {string} userEmail citizen user email
   * @param {string} userPassword citizen user email
   * @param {string} caseData case data to create case with (name, email)
   */
  async createCase(
    userId: string,
    userEmail: string,
    userPassword: string,
    caseData: Record<string, string>
  ): Promise<string> {
    const eventId = 'citizen-create-application' as string;
    // auth token generated by user who wants to create case, this should be passed in to createCase method
    const authToken = await this.idamUtils.generateIdamToken({
      grantType: 'password',
      username: userEmail as string,
      password: userPassword as string,
      clientId: 'adoption-web',
      clientSecret: process.env.IDAM_SECRET as string,
      scope: 'openid profile roles',
    });
    console.log(authToken);
    process.env.CREATE_CASE_TOKEN = authToken;
    const eventToken: string = await this.getEventToken(userId, authToken, eventId);
    const accessToken: AxiosResponse<string> | undefined = await getAccessToken(userEmail, userPassword);
    const context = await this.createApiContext();
    const serviceToken = getServiceAuthToken();
    const response = await context.post(`${urlConfig.ccd_data_api_url}/case-types/${this.caseType}/cases`, {
      headers: {
        Authorization: `Bearer ${accessToken}`,
        ServiceAuthorization: serviceToken,
        Accept: 'application/json',
        'Content-Type': 'application/json',
        experimental: 'true',
      },
      data: {
        data: caseData,
        event: { id: eventId },
        event_token: eventToken,
      },
    });

    if (!response.ok()) {
      throw new Error(`Failed to create case: ${response.status()}`);
    }

    const json = await response.json();
    json.data.status = json.state;
    return json;
  }

  /**
   * Function to retrieve the event for a given event ID.
   */
  private async getEventToken(userId: string, bearerToken: string, eventId: string): Promise<string> {
    let eventToken = '';
    const serviceToken = await getTokenFromApi();
    const context = await this.createApiContext();
    const url = `${urlConfig.ccd_data_api_url}/case-types/A58/event-triggers/citizen-create-application`;

    const response = await context.get(url, {
      headers: {
        accept: 'application/vnd.uk.gov.hmcts.ccd-data-store-api.start-case-trigger.v2+json;charset=UTF-8',
        Authorization: `Bearer ${bearerToken}`,
        experimental: 'true',
        ServiceAuthorization: `${serviceToken}`,
      },
    });
    if (response.ok()) {
      const responseBody = await response.json();
      if (responseBody) {
        eventToken = responseBody.token;
      } else {
        throw new Error('Failed to get event token');
      }
    } else {
      throw new Error(
        `Failed to get event token for event: ${eventId}: Received the following response: ${response.status()} - ${response.statusText()}`
      );
    }
    return eventToken;
  }

  async triggerEvent(
    userId: string,
    caseId: string,
    eventId: string,
    eventData: Record<string, never>
  ): Promise<string> {
    const context = await this.createApiContext();
    const token = await this.getEventToken(userId, process.env.CREATE_CASE_TOKEN as string, eventId);
    const serviceToken = await this.getServiceToken();
    const response = await context.post(`/cases/${caseId}/events`, {
      headers: {
        Authorization: `Bearer ${process.env.CREATE_CASE_TOKEN}`,
        ServiceAuthorization: serviceToken,
        Accept: 'application/json',
        'Content-Type': 'application/json',
        experimental: 'true',
      },
      data: {
        event: { id: eventId },
        data: eventData,
        event_token: token,
      },
    });
    if (!response.ok()) {
      throw new Error(`Failed to trigger event "${eventId}": ${response.status()}`);
    }
    return response.json();
  }

  async triggerMultipleEvents(
    userId: string,
    caseId: string,
    events: { eventName: string; eventData: Record<string, never> }[]
  ): Promise<string[]> {
    const results: string[] = [];
    for (const { eventName, eventData } of events) {
      const result = await this.triggerEvent(userId, caseId, eventName, eventData);
      results.push(result);
    }
    return results;
  }
}
