services:
  authProvider:
    url: SERVICE_AUTH_PROVIDER_URL
    secret: SERVICE_AUTH_SECRET
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    clientSecret: IDAM_SECRET
    userRole: IDAM_ROLE
  case:
    url: CCD_URL
  location_api:
    url: LOCATION_API_URL
  payments:
    url: PAYMENTS_API_URL
  feeLookup:
    url: FEE_LOOKUP_URL
  documentManagement:
    url: DOCUMENT_MANAGEMENT_URL
  cdam:
    url: CDAM_API_URL
  equalityAndDiversity:
    url: EQUALITY_URL
    tokenKey: PCQ_TOKEN
    pcqEnabled: PCQ_ENABLED
  pact:
    tag: PACT_TAG
  draftStore:
    redis:
      host: REDIS_HOST
      tls: REDIS_TLS
      port: REDIS_PORT
      ttl: REDIS_TTL_MS
port: PORT
session:
  redis:
    host: REDIS_HOST
  secureCookie: SECURE_COOKIE
e2e:
  userTestPassword: TEST_PASSWORD
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
localCourt:
  emailId:
    CHELMSFORD_FAMILY_COURT: CHELMSFORD_FAMILY_COURT_EMAIL
    OXFORD_FAMILY_COURT: OXFORD_FAMILY_COURT_EMAIL
    MEDWAY_FAMILY_COURT: MEDWAY_FAMILY_COURT_EMAIL
    PORTSMOUTH_FAMILY_COURT: PORTSMOUTH_FAMILY_COURT_EMAIL
    LEEDS_FAMILY_COURT: LEEDS_FAMILY_COURT_EMAIL
    NORTHAMPTON_FAMILY_COURT: NORTHAMPTON_FAMILY_COURT_EMAIL
    WORCESTER_FAMILY_COURT: WORCESTER_FAMILY_COURT_EMAIL
    NEWPORT_GWENT_FAMILY_COURT: NEWPORT_GWENT_FAMILY_COURT_EMAIL
    FALLBACK_EMAIL_ID: FALLBACK_EMAIL_ID_VALUE
    LIVERPOOL_FAMILY_COURT: LIVERPOOL_FAMILY_COURT_EMAIL
    CENTRAL_LONDON_FAMILY_COURT: CENTRAL_LONDON_FAMILY_COURT_EMAIL
    READING_FAMILY_COURT: READING_FAMILY_COURT_EMAIL
    STOKE-ON-TRENT_FAMILY_COURT: STOKE-ON-TRENT_FAMILY_COURT_EMAIL
    LEICESTER_FAMILY_COURT: LEICESTER_FAMILY_COURT_EMAIL
    LINCOLN_FAMILY_COURT: LINCOLN_FAMILY_COURT_EMAIL
    NOTTINGHAM_FAMILY_COURT: NOTTINGHAM_FAMILY_COURT_EMAIL
    DERBY_FAMILY_COURT: DERBY_FAMILY_COURT_EMAIL
    COVENTRY_FAMILY_COURT: COVENTRY_FAMILY_COURT_EMAIL
    BIRMINGHAM_FAMILY_COURT: BIRMINGHAM_FAMILY_COURT_EMAIL
    WOLVERHAMPTON_FAMILY_COURT: WOLVERHAMPTON_FAMILY_COURT_EMAIL
    SWINDON_FAMILY_COURT: SWINDON_FAMILY_COURT_EMAIL
    PLYMOUTH_FAMILY_COURT: PLYMOUTH_FAMILY_COURT_EMAIL
    TAUNTON_FAMILY_COURT: TAUNTON_FAMILY_COURT_EMAIL
    TRURO_FAMILY_COURT: TRURO_FAMILY_COURT_EMAIL
    BOURNEMOUTH_FAMILY_COURT: BOURNEMOUTH_FAMILY_COURT_EMAIL
    BRISTOL_FAMILY_COURT: BRISTOL_FAMILY_COURT_EMAIL
    GLOUCESTERSHIRE_FAMILY_COURT: GLOUCESTERSHIRE_FAMILY_COURT_EMAIL
    WEST_LONDON_FAMILY_COURT: WEST_LONDON_FAMILY_COURT_EMAIL
    BARNET_FAMILY_COURT: BARNET_FAMILY_COURT_EMAIL
    BROMLEY_FAMILY_COURT: BROMLEY_FAMILY_COURT_EMAIL
    CENTRAL_FAMILY_COURT: CENTRAL_FAMILY_COURT_EMAIL
    CROYDON_FAMILY_COURT: CROYDON_FAMILY_COURT_EMAIL
    EAST_LONDON_FAMILY_COURT: EAST_LONDON_FAMILY_COURT_EMAIL
    LUTON_FAMILY_COURT: LUTON_FAMILY_COURT_EMAIL
    NORWICH_FAMILY_COURT: NORWICH_FAMILY_COURT_EMAIL
    WATFORD_FAMILY_COURT: WATFORD_FAMILY_COURT_EMAIL
    PETERBOROUGH_FAMILY_COURT: PETERBOROUGH_FAMILY_COURT_EMAIL
    BRIGHTON_FAMILY_COURT: BRIGHTON_FAMILY_COURT_EMAIL
    GUILDFORD_FAMILY_COURT: GUILDFORD_FAMILY_COURT_EMAIL
    MILTON_KEYNES_FAMILY_COURT: MILTON_KEYNES_FAMILY_COURT_EMAIL
    KINGSTON_UPON_HULL_FAMILY_COURT: KINGSTON_UPON_HULL_FAMILY_COURT_EMAIL
    NEWCASTLE_UPON_TYNE_FAMILY_COURT: NEWCASTLE_UPON_TYNE_FAMILY_COURT_EMAIL
    TEESSIDE_FAMILY_COURT: TEESSIDE_FAMILY_COURT_EMAIL
    YORK_FAMILY_COURT: YORK_FAMILY_COURT_EMAIL
    SHEFFIELD_FAMILY_COURT: SHEFFIELD_FAMILY_COURT_EMAIL
    CHESTER_FAMILY_COURT: CHESTER_FAMILY_COURT_EMAIL
    BARROW-IN-FURNESS_FAMILY_COURT: BARROW-IN-FURNESS_FAMILY_COURT_EMAIL
    BLACKBURN_FAMILY_COURT: BLACKBURN_FAMILY_COURT_EMAIL
    CARLISLE_FAMILY_COURT: CARLISLE_FAMILY_COURT_EMAIL
    WEST_CUMBRIA_FAMILY_COURT: WEST_CUMBRIA_FAMILY_COURT_EMAIL
    MANCHESTER_FAMILY_COURT: MANCHESTER_FAMILY_COURT_EMAIL
    ABERYSTWYTH_FAMILY_COURT: ABERYSTWYTH_FAMILY_COURT_EMAIL
    CAERNARFON_FAMILY_COURT: CAERNARFON_FAMILY_COURT_EMAIL
    CARDIFF_FAMILY_COURT: CARDIFF_FAMILY_COURT_EMAIL
    HAVERFORDWEST_FAMILY_COURT: HAVERFORDWEST_FAMILY_COURT_EMAIL
    LLANELLI_FAMILY_COURT: LLANELLI_FAMILY_COURT_EMAIL
    PONTYPRIDD_FAMILY_COURT: PONTYPRIDD_FAMILY_COURT_EMAIL
    PORT_TALBOT_FAMILY_COURT: PORT_TALBOT_FAMILY_COURT_EMAIL
    PRESTATYN_FAMILY_COURT: PRESTATYN_FAMILY_COURT_EMAIL
    SWANSEA_FAMILY_COURT: SWANSEA_FAMILY_COURT_EMAIL
    WREXHAM_FAMILY_COURT: WREXHAM_FAMILY_COURT_EMAIL
fpl:
  localAuthority:
    COR: COR_VAL
    WOL: WOL_VAL
    SMC: SMC_VAL
    TWB: TWB_VAL
    SHR: SHR_VAL
    WAL: WAL_VAL
    BCC: BCC_VAL
    CMB: CMB_VAL
    BOL: BOL_VAL
    HBC: HBC_VAL
    WIR: WIR_VAL
    GTE: GTE_VAL
    YCC: YCC_VAL
    BHC: BHC_VAL
    TBC: TBC_VAL
    DEV: DEV_VAL
    PEM: PEM_VAL
    BNS: BNS_VAL
    GCC: GCC_VAL
    LBC: LBC_VAL
    NYS: NYS_VAL
    WIC: WIC_VAL
    PET: PET_VAL
    SGL: SGL_VAL
    HAM: HAM_VAL
    VOG: VOG_VAL
    NPT: NPT_VAL
    NTH: NTH_VAL
    CAR: CAR_VAL
    GSCC: GSCC_VAL
    LBTH: LBTH_VAL
    BRD: BRD_VAL
    SUF: SUF_VAL
    WRX: WRX_VAL
    NFK: NFK_VAL
    NWT: NWT_VAL
    SHF: SHF_VAL
    ROT: ROT_VAL
    DON: DON_VAL
    BAR: BAR_VAL
    IOA: IOA_VAL
    KECH: KECH_VAL
    WMS: WMS_VAL
    DEN: DEN_VAL
    CWC: CWC_VAL
    BRE: BREv
    CPY: CPY_VAL
    WAR: WAR_VAL
    BGW: BGW_VAL
    NHB: NHB_VAL
    STH: STH_VAL
    MON: MON_VAL
    BRO: BRO_VAL
    KKL: KKL_VAL
    LEE: LEE_VAL
    BED: BED_VAL
    FCC: FCC_VAL
    CON: CON_VAL
    SBC: SBC_VAL
    HRW: HRW_VAL
    HPL: HPL_VAL
    CBF: CBF_VAL
    SWK: SWK_VAL
    HUL: HUL_VAL
    BLA: BLA_VAL
    NTY: NTY_VAL
    KEN: KEN_VAL
    MCC: MCC_VAL
    CAM: CAM_VAL
    POW: POW_VAL
    SUN: SUN_VAL
    IOW: IOW_VAL
    BFO: BFO_VAL
    WBC: WBC_VAL
    SCF: SCF_VAL
    WIM: WIM_VAL
    WOK: WOK_VAL
    TCBC: TCBC_VAL
    KGN: KGN_VAL
    RMD: RMD_VAL
    WAD: WAD_VAL
    GRW: GRW_VAL
    TOR: TOR_VAL
    PLY: PLY_VAL
    BRA: BRA_VAL
    CAL: CAL_VAL
    RBC: RBC_VAL
    SAL: SAL_VAL
    ESX: ESX_VAL
    HAF: HAF_VAL
    REC: REC_VAL
    NTHW: NTHW_VAL
    NTHN: NTHN_VAL
    LAM: LAM_VAL
    ISL: ISL_VAL
    CDN: CDN_VAL
    LEW: LEW_VAL
    BNT: BNT_VAL
    HLW: HLW_VAL
    WSX: WSX_VAL
    BAD: BAD_VAL
    ENF: ENF_VAL
    WAF: WAF_VAL
    CRY: CRY_VAL
    RED: RED_VAL
    HAR: HAR_VAL
    EAL: EAL_VAL
    BEX: BEX_VAL
    BUR: BUR_VAL
    ESS: ESS_VAL
    HAC: HAC_VAL
    COL: COL_VAL
    HAV: HAV_VAL
    NEW: NEW_VAL
    RTL: RTL_VAL
    STCC: STCC_VAL
    SSCC: SSCC_VAL
    LCC: LCC_VAL
    LSCC: LSCC_VAL
    NCC: NCC_VAL
    NSCC: NSCC_VAL
    DCC: DCC_VAL
    DCOC: DCOC_VAL
    CCC: CCC_VAL
    WCC: WCC_VAL
    BCCO: BCCO_VAL
    SMBC: SMBC_VAL
    WSCC: WSCC_VAL
    HSCC: HSCC_VAL
    DMBC: DMBC_VAL
    PCCL: PCCL_VAL
    SCC: SCC_VAL
    WSC: WSC_VAL
    SBCO: SBCO_VAL
    SCCO: SCCO_VAL
    BCPC: BCPC_VAL
    DCCO: DCCO_VAL
    LBH: LBH_VAL
    RBK: RBK_VAL
    LBKT: LBKT_VAL
    LBS: LBS_VAL
    COLO: COLO_VAL
    LBSM: LBSM_VAL
    RBCO: RBCO_VAL
    SBOC: SBOC_VAL
    OSCC: OSCC_VAL
    TBCO: TBCO_VAL
    SOSBC: SOSBC_VAL
    HSCCO: HSCCO_VAL
    RCC: RCC_VAL
    CCCO: CCCO_VAL
    MEDC: MEDC_VAL
    MKC: MKC_VAL
    BSCC: BSCC_VAL
    KUHCC: KUHCC_VAL
    ERY: ERY_VAL
    NLSC: NLSC_VAL
    NELS: NELS_VAL
    NCCC: NCCC_VAL
    STMBC: STMBC_VAL
    DBC: DBC_VAL
    DURCC: DURCC_VAL
    MBC: MBC_VAL
    STBC: STBC_VAL
    WAK: WAK_VAL
    LIV: LIV_VAL
    KNO: KNO_VAL
    CHE: CHE_VAL
    CNW: CNW_VAL
    LSCCO: LSCCO_VAL
    BDBC: BDBC_VAL
    OLD: OLD_VAL
    STO: STO_VAL
    TAM: TAM_VAL
    SWCC: SWCC_VAL
    CER: CER_VAL
    CARC: CARC_VAL
    MTC: MTC_VAL
    SEWAS: SEWAS_VAL
    RCT: RCT_VAL
    CYG: CYG_VAL
    CSYM: CSYM_VAL
    GWC: GWC_VAL
socialWorker:
  supportedDomains: SOCIAL_WORKER_SUPPORTED_DOMAINS

adoption:
  family-court:
    family-court-Leicester: LEICESTER_VAL
    family-court-Stoke-on-Trent: STOKE-ON-TRENT_VAL
    family-court-Lincoln: LINCOLN_VAL
    family-court-Northampton: NORTHAMPTON_VAL
    family-court-Nottingham: NOTTINGHAM_VAL
    family-court-Derby: DERBY_VAL
    family-court-Coventry: COVENTRY_VAL
    family-court-Birmingham: BIRMINGHAM_VAL
    family-court-Worcester: WORCESTER_VAL
    family-court-Wolverhampton: WOLVERHAMPTON_VAL
    family-court-Portsmouth: PORTSMOUTH_VAL
    family-court-Swindon: SWINDON_VAL
    family-court-Plymouth: PLYMOUTH_VAL
    family-court-Taunton: TAUNTON_VAL
    family-court-Truro: TRURO_VAL
    family-court-Bournemouth: BOURNEMOUTH_VAL
    family-court-Bristol: BRISTOL_VAL
    family-court-Gloucestershire: GLOUCESTERSHIRE_VAL
    family-court-West-London: WEST-LONDON_VAL
    family-court-Barnet: BARNET_VAL
    family-court-Bromley: BROMLEY_VAL
    family-court-Central: CENTRAL_VAL
    family-court-Croydon: CROYDON_VAL
    family-court-East-London: EAST-LONDON_VAL
    family-court-Luton: LUTON_VAL
    family-court-Reading: READING_VAL
    family-court-Oxford: OXFORD_VAL
    family-court-Chelmsford: CHELMSFORD_VAL
    family-court-Norwich: NORWICH_VAL
    family-court-Watford: WATFORD_VAL
    family-court-Peterborough: PETERBOROUGH_VAL
    family-court-Brighton: BRIGHTON_VAL
    family-court-Guildford: GUILDFORD_VAL
    family-court-Medway: MEDWAY_VAL
    family-court-Milton-Keynes: MILTON-KEYNES_VAL
    family-court-Kingston-upon-Hull: KINGSTON-UPON-HULL_VAL
    family-court-Newcastle-upon-Tyne: NEWCASTLE-UPON-TYNE_VAL
    family-court-Teesside: TEESSIDE_VAL
    family-court-York: YORK_VAL
    family-court-Leeds: LEEDS_VAL
    family-court-Sheffield: SHEFFIELD_VAL
    family-court-Liverpool: LIVERPOOL_VAL
    family-court-Chester: CHESTER_VAL
    family-court-Barrow-in-Furness: BARROW-IN-FURNESS_VAL
    family-court-Blackburn: BLACKBURN_VAL
    family-court-Carlisle: CARLISLE_VAL
    family-court-West-Cumbria: WEST-CUMBRIA_VAL
    family-court-Manchester: MANCHESTER_VAL
    family-court-Aberystwyth: ABERYSTWYTH_VAL
    family-court-Caernarfon: CAERNARFON_VAL
    family-court-Cardiff: CARDIFF_VAL
    family-court-Haverfordwest: HAVERFORDWEST_VAL
    family-court-Llanelli: LLANELLI_VAL
    family-court-Newport: NEWPORT_VAL
    family-court-Pontypridd: PONTYPRIDD_VAL
    family-court-Port-Talbot: PORT-TALBOT_VAL
    family-court-Prestatyn: PRESTATYN_VAL
    family-court-Swansea: SWANSEA_VAL
    family-court-Wrexham: WREXHAM_VAL
