localCourt:
  emailId:
    CHELMSFORD_FAMILY_COURT: 'chelmsfordadoptionapplication@justice.gov.uk'
    OXFORD_FAMILY_COURT: 'Oxfordadoptionapplication@justice.gov.uk'
    MEDWAY_FAMILY_COURT: 'Medwayadoptionapplication@justice.gov.uk'
    PORTSMOUTH_FAMILY_COURT: 'PortsmouthAdoptionApplication@justice.gov.uk'
    #Leedsadoptionapplication@justice.gov.uk(Business has asked to update Leeds court email id)
    LEEDS_FAMILY_COURT: 'adoptionsleeds@justice.gov.uk'
    NORTHAMPTON_FAMILY_COURT: 'Northamptonadoptionapplications@justice.gov.uk'
    WORCESTER_FAMILY_COURT: 'Worcesteradoptionapplication@justice.gov.uk'
    NEWPORT_GWENT_FAMILY_COURT: 'NewportGwentadoptionapplication@justice.gov.uk'
    FALLBACK_EMAIL_ID: 'adoptionproject@justice.gov.uk'
